### ISSUE TITLE
Doesn't work in emulator / device

### ISSUE THREAD

**Issue by hounsellal** [aaronksaunders/ionic2-angularfire-sample#13]
Hi there,

I've followed your code in order to figure out firebase auth with angular2/ionic2/angulafire2. It's helpful and everything works perfectly in the browser with ionic serve. It phones into firebase, sees whether the user is logged in and, if not, redirects to a login form (I used a separate page rather than a modal).

However, when I run this on ios emulator, it doesn't work at all. It never pushes the login form, but just opens the main page. I'm only using email authentication and it doesn't seem to retrieve any auth information at all. 

When I ran the debugger in Safari while Simulator was open I did see this error:
"Error: This operation is not supported in the environment this application is running on. "location.protocol" must be http or https and web storage must be enabled."

Any ideas?

**Comment by Vasanth19** [comment]
+1, 

I have the same issue. Looks like this issue is not only relevant to auth but also affecting all the firebase calls from the device. Not sure if there any fix for this. 
this.items = this.af.database.list('/items');


@aaronksaunders -   Any thoughts?

**Comment by dc-apps** [comment]
+1,

There are two issues, as far as I can see:
1) firebase3 sends some api call (iframe stuff) to "//apis.google/etc", which is normally fine – but cordova runs on "file://" and not "http(s)://", so it's not found. You _could_ change this in firebase.js (node_modules).
2) It complains about domain not being authorized. Adding 127.0.0.1 to firebase console doesn't help...

**Comment by austinheinrichs** [comment]
First, thanks for the very helpful repo.  Anyone have any luck on getting this to work?  I'm also running into the same issue.

**Comment by aaronksaunders** [comment]
I will look into this today. But please make sure you have set your` package.json` to match the exact same versions that I am using in the sample code. I am certain that this code works properly based on the specified versions.

**Comment by austinheinrichs** [comment]
Thank you for the update Aaron.  Below is my ionic info as well as my node dependencies:
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.1.0-beta.3
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a 

  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "2.0.0-rc.2",
    "es6-shim": "0.35.0",
    "ionic-angular": "2.0.0-beta.11",
    "ionic-native": "^1.3.10",
    "ionicons": "3.0.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12",
    "angularfire2": "2.0.0-beta.2",
    "firebase": "3.3.0",
    "moment": "2.13.0"
  }

**Comment by aaronksaunders** [comment]
check build, I believe I have addressed the issue, https://github.com/aaronksaunders/ionic2-angularfire-sample/commit/10e3adff96445c790847982afc72cba8b474b57b

**Comment by austinheinrichs** [comment]
Thank you for taking a look Aaron.  I pulled in your last commit and am still getting the same result.  I did some additional digging and @dc-apps first point seems to be the issue in my project.  I am getting the error from an observable which I assume is from AngularFire, but haven't finished narrowing it down.  Not sure if its the same issue here.

**Comment by aaronksaunders** [comment]
@austinheinrichs did you delete the `node_modules` directory and run `npm install` after pulling the code?

**Comment by austinheinrichs** [comment]
Aaron, I actually re-cloned the project and ran an npm install from a clean slate.

**Comment by aaronksaunders** [comment]
i have re-run the cloned project multiple times and it works fine... you will need to provide additional information in order for me to try and help you.

**Comment by austinheinrichs** [comment]
Aaron, after rebuilding again I found that it works without livereload enabled.  Sorry for not mentioning that.

**Comment by austinheinrichs** [comment]
This leaves me with a follow up question.  I noticed in the last commit that you actually replaced your subscription to an angularfire observable with the normal firebase javascript sdk.  Is there a reason that using the observable doesn't work?  In my project it almost looks like all the subscriptions to angularfire observables are causing errors.  Can you shed any light on this?  For example when I subscribe to a database list like so:

    getAllObjects():Observable<IObject[]> {
        return this._af.database.list('/objects')
        .map((results) => <IObject[]>results)
        .catch(this.handleError);
    }

The above causes an error saying Network Error: Protocol Not Available.  In my system log I see:  nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed.

**Comment by aaronksaunders** [comment]
it is quite possible.

just to let you know, we don't use angularFire2 with any client work now
because it is still beta, it is changing and it doesn't support the full
feature set of firebase. Unless there is a compelling reason to fight
through the issues of AngularFire2 i would recommend treating it like beta
software and use the default Firebase javascript library for
production/client facing solutions


--

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders




This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by austinheinrichs** [comment]
I will keep that in mind.  Thank you for your help!
